x-node: &node
  build:
    context: .
    dockerfile: pipeshub-dockerfile
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - BPF
    - PERFMON
  security_opt:
    - seccomp:unconfined
  volumes:
    - ./certs/fullchain.pem:/app/certs/fullchain.pem:ro
    - ./certs/privkey.pem:/app/certs/privkey.pem:ro
  environment:
    REDIS_URL: redis://192.168.102.5:6379/0
    PORT: 16916
    HTTPS_PORT: 16917
    SOCKET_PORT: 3000
    JWT_SECRET: SOME-LONG-RANDOM-STRING-HERE-USING-OPENSSL-RANDOM-SECRET
  depends_on:
    - redis
  restart: unless-stopped

services:

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      net-bridge:
        ipv4_address: 192.168.102.5
    restart: unless-stopped

  node-a:
    <<: *node
    ports:
      - "80:16916"
      - "443:16917"
      - "3000:3000"
    networks:
      net-bridge:
        ipv4_address: 192.168.102.2

  node-b:
    <<: *node
    networks:
      net-bridge:
        ipv4_address: 192.168.102.3

  node-c:
    <<: *node
    networks:
      net-bridge:
        ipv4_address: 192.168.102.4

networks:
  net-bridge:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1460"
    ipam:
      config:
        - subnet: 192.168.102.0/24
          gateway: 192.168.102.1

volumes:
  redis-data: